@startuml
|a| แอดมิน
|b| ระบบ
|c| ข้อมูลผู้ใช้งาน

|a|
start
:เปิดแอปพลิเคชัน;
:เข้าสู่แอปพลิเคชัน;
|b|
:เข้าสู่ระบบ;
|a|
:หน้าต่างแก้ไขข้อมูลผู้ใช้งาน;
|c|
:แสดงข้อมูลของผู้ใช้งานทั้งหมด
ชื่อ นามสกุล อายุ ที่อยู่ ประจำตัว เป็นต้น;
:แก้ไข้ข้อมูลของผู้ใช้งานทั้งหมด
ชื่อ นามสกุล อายุ ที่อยู่ ประจำตัว เป็นต้น;
|a|
:หน้าต่างแจ้งเตือนการร้องขอ
เข้าดูข้อมูลผู้ใช้งาน;
|b|
:แจ้งเตือนการร้องขอข้อมูล;
:ออกจากระบบ;
stop
@enduml
