@startuml
|a| ผู้เยี่ยมชม
|b| ระบบ
|c| ข้อมูลผู้ใช้งาน
|d| แผนที่


|a|
start
:เปิดแอปพลิเคชัน;
:เข้าสู่แอปพลิเคชัน;
:หน้าต่างผู้เยี่ยมชม;
|b|
:สแกนคิวอาร์โค้ด;
:รอการยืนยันข้อมูล;
|c|
:เข้าดูข้อมูลผู้ใช้งาน;
|d|
:ใช้งานgooglemapเผื่อนำทาง;
stop



@enduml