@startuml
|a| ผู้ใช้งาน
|b| ระบบ
|c| ข้อมูลผู้ใช้งาน


|a|
start
:เปิดแอปพลิเคชัน;
:เข้าสู่ระบบ;

|b|
repeat
repeat while  (สมัครสมาชิก) is (ไม่เป็นสมาชิก) not (เป็นสมาชิก)
|a|
:หน้าจอหลัก;
|c|
:ผู้ใช้งานดูข้อมูลส่วนตัว;
|b|
:ออกจากระบบ;
stop














@enduml