@startuml
skinparam classAttributeIconSize 0

class MainPage {
  + navigateToUserLogin()
  + navigateToAdminLogin()
  + navigateToGuest()
}

class User {
  - Name: String
  - Surname: String
  - Address: String
  - Phone: String
  - RelativeAddress: String
  - ChronicDisease: String
  - Gender: String
  - Age: int
  - MaritalStatus: String
  - EducationStatus: String
  

  + displayUser()
}
class Admin {

    + addUser()
    + removeUser()
    + editUser()
    + updateUser()
    + Check_PermisionforGuest()
    + NotificationFromGuest()

}
class LoginUserHandler{
  - Id_User : String
  - Password_User : String

  + Check_user()
  + Verification()
}
class LoginAdminHandler{
  - Id_User : String
  - Password_User : String

  + Check_admin()
  + Verification()
}
class Guest {
  - Guest_id : String

  +qr_codescan()

}
class Check_Permision_ForData{
  
  + SendRequestoAdmin(Req:Check_PermisionforGuest):bool
}
class Data_Display_ForGuest{

  + DisplayUserData(Req:alldatafron Class User)
}



MainPage --> LoginUserHandler : Include
MainPage --> LoginAdminHandler : Include
MainPage "1"-- "1..*" Guest 


LoginUserHandler --o User 
LoginAdminHandler --o Admin 

Check_Permision_ForData ..|> Guest
Check_Permision_ForData "1..*" -- "1" Admin
@enduml
